version: '3.5'

services:
  redis:
    image: redis:latest
    container_name: launchpad_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis-1234
      - REDIS_PORT=6379
    restart: unless-stopped
    
volumes:
  redis_data: